name: Publish Draft Release on 21 Nov 2025 at 12:00 UTC

on:
  schedule:
    - cron: "0 12 21 11 *"  # 21. November um 12:00 UTC
  workflow_dispatch:        # Ermöglicht manuelles Auslösen (optional)

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: Publish the latest draft release
        uses: eregon/publish-release@v1
        with:
          release: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
